name: Build and Run Backend (Dockerfile only)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ ดึงโค้ดจาก GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ ตั้งค่า Java (เพราะคุณใช้ Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Build ด้วย Gradle
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 4️⃣ Build Docker image จาก Dockerfile โดยตรง
      - name: Build Docker image
        run: |
          docker build -t hello-devops-backend:latest .

      # 5️⃣ ทดสอบรัน container (optional)
      - name: Run container for test
        run: |
          docker run -d --name backend-test -p 8080:8080 hello-devops-backend:latest
          sleep 5
          docker ps
          docker logs backend-test || true

      # 6️⃣ Clean up
      - name: Clean up containers
        if: always()
        run: |
          docker stop backend-test || true
          docker rm backend-test || true
